interface:
  customerProvision: "CustomerProvision"
customerProvision:
  xsd: "xsd/request/CustomerProvision_request_v2.xsd"
demo:
  dynamicRouting:
    uri: http://192.168.40.14:31659/dynamicConfig/spain/td
  error:
    uri: http://192.168.40.14:31659/dynamicConfig/spain/td/error
local:
  dynamicRouting:
    uri: http://localhost:8081/dynamicConfig/spain/td
  error:
    uri: http://localhost:8081/dynamicConfig/spain/td/error
server:
  port: 8085
