server:
 port: 8888

webservice:
 identitymanagement:
  uri: "/ws"
  targetNamespace: "http://www.telefonica.com/wsdl/UNICA/SOAP/IAM_IdentityManagement/v2/local"
  xsd: "wsdl/identityManagement/UNICA_API_SOAP_IAM_IdentityManagement_Extensions_v1_0.xsd"
 northbound:
  provManagement:
   uri: "/ws"
   targetNamespace: "http://www.telefonica.com/wsdl/UNICA/SOAP/OProv_Management/v7/local"
   xsd: "wsdl/northbound/provManagement/UNICA_API_SOAP_OProv_Management_v7_1.xsd"
 
dynamicRouting:
  uri: http://localhost:8081/dynamicConfig/unica/td
