<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="TD_SubscriptionService"
	targetNamespace="GVP.GAL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
	xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
	xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="GVP.GAL" xmlns:wsa10="http://www.w3.org/2005/08/addressing"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
	<wsdl:types>
		<xs:schema elementFormDefault="qualified" targetNamespace="GVP.GAL"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:import namespace="http://www.telefonica.com/ServiceId" />
			<xs:import
				namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
			<xs:import namespace="http://schemas.datacontract.org/2004/07/System" />
			<xs:import namespace="http://schemas.datacontract.org/2004/07/GVP.GAL.API" />
			<xs:element name="AddMultipleSubscription">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="instanceId" type="xs:int" />
						<xs:element minOccurs="0" name="platformId" type="xs:int" />
						<xs:element minOccurs="0" name="serviceId" type="q1:ServiceIdType"
							xmlns:q1="http://www.telefonica.com/ServiceId" />
						<xs:element minOccurs="0" name="uniqueId" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="productIds" nillable="true"
							type="q2:ArrayOfstring" xmlns:q2="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
						<xs:element minOccurs="0" name="endDates" nillable="true"
							type="q3:ArrayOfNullableOfdateTime" xmlns:q3="http://schemas.datacontract.org/2004/07/System" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="AddMultipleSubscriptionResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="AddMultipleSubscriptionResult"
							nillable="true" type="q4:ResultDataContractOfboolean"
							xmlns:q4="http://schemas.datacontract.org/2004/07/GVP.GAL.API" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RemoveMultipleSubscription">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="instanceId" type="xs:int" />
						<xs:element minOccurs="0" name="platformId" type="xs:int" />
						<xs:element minOccurs="0" name="serviceId" type="q5:ServiceIdType"
							xmlns:q5="http://www.telefonica.com/ServiceId" />
						<xs:element minOccurs="0" name="uniqueId" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="productIds" nillable="true"
							type="q6:ArrayOfstring" xmlns:q6="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
						<xs:element minOccurs="0" name="endDates" nillable="true"
							type="q7:ArrayOfNullableOfdateTime" xmlns:q7="http://schemas.datacontract.org/2004/07/System" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RemoveMultipleSubscriptionResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0"
							name="RemoveMultipleSubscriptionResult" nillable="true"
							type="q8:ResultDataContractOfboolean" xmlns:q8="http://schemas.datacontract.org/2004/07/GVP.GAL.API" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RemoveScheduledSubscriptions">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="instanceId" type="xs:int" />
						<xs:element minOccurs="0" name="platformId" type="xs:int" />
						<xs:element minOccurs="0" name="serviceId" type="q9:ServiceIdType"
							xmlns:q9="http://www.telefonica.com/ServiceId" />
						<xs:element minOccurs="0" name="uniqueId" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="productIds" nillable="true"
							type="q10:ArrayOfstring" xmlns:q10="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RemoveScheduledSubscriptionsResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0"
							name="RemoveScheduledSubscriptionsResult" nillable="true"
							type="q11:ResultDataContractOfboolean" xmlns:q11="http://schemas.datacontract.org/2004/07/GVP.GAL.API" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
		<xs:schema attributeFormDefault="qualified"
			elementFormDefault="qualified"
			targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
			<xs:element name="anyType" nillable="true" type="xs:anyType" />
			<xs:element name="anyURI" nillable="true" type="xs:anyURI" />
			<xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
			<xs:element name="boolean" nillable="true" type="xs:boolean" />
			<xs:element name="byte" nillable="true" type="xs:byte" />
			<xs:element name="dateTime" nillable="true" type="xs:dateTime" />
			<xs:element name="decimal" nillable="true" type="xs:decimal" />
			<xs:element name="double" nillable="true" type="xs:double" />
			<xs:element name="float" nillable="true" type="xs:float" />
			<xs:element name="int" nillable="true" type="xs:int" />
			<xs:element name="long" nillable="true" type="xs:long" />
			<xs:element name="QName" nillable="true" type="xs:QName" />
			<xs:element name="short" nillable="true" type="xs:short" />
			<xs:element name="string" nillable="true" type="xs:string" />
			<xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
			<xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
			<xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
			<xs:element name="unsignedShort" nillable="true"
				type="xs:unsignedShort" />
			<xs:element name="char" nillable="true" type="tns:char" />
			<xs:simpleType name="char">
				<xs:restriction base="xs:int" />
			</xs:simpleType>
			<xs:element name="duration" nillable="true" type="tns:duration" />
			<xs:simpleType name="duration">
				<xs:restriction base="xs:duration">
					<xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
					<xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
					<xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
				</xs:restriction>
			</xs:simpleType>
			<xs:element name="guid" nillable="true" type="tns:guid" />
			<xs:simpleType name="guid">
				<xs:restriction base="xs:string">
					<xs:pattern
						value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
				</xs:restriction>
			</xs:simpleType>
			<xs:attribute name="FactoryType" type="xs:QName" />
			<xs:attribute name="Id" type="xs:ID" />
			<xs:attribute name="Ref" type="xs:IDREF" />
		</xs:schema>
		<xs:schema elementFormDefault="qualified"
			targetNamespace="http://www.telefonica.com/ServiceId" xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns:tns="http://www.telefonica.com/ServiceId">
			<xs:simpleType name="ServiceIdType">
				<xs:restriction base="xs:string">
					<xs:enumeration value="Unknown" />
					<xs:enumeration value="OTT" />
					<xs:enumeration value="IPTV" />
					<xs:enumeration value="OTT and IPTV" />
				</xs:restriction>
			</xs:simpleType>
			<xs:element name="ServiceIdType" nillable="true"
				type="tns:ServiceIdType" />
		</xs:schema>
		<xs:schema elementFormDefault="qualified"
			targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
			<xs:complexType name="ArrayOfstring">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="string"
						nillable="true" type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfstring" nillable="true"
				type="tns:ArrayOfstring" />
		</xs:schema>
		<xs:schema elementFormDefault="qualified"
			targetNamespace="http://schemas.datacontract.org/2004/07/System"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/System">
			<xs:complexType name="ArrayOfNullableOfdateTime">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="dateTime"
						nillable="true" type="xs:dateTime" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfNullableOfdateTime" nillable="true"
				type="tns:ArrayOfNullableOfdateTime" />
		</xs:schema>
		<xs:schema elementFormDefault="qualified"
			targetNamespace="http://schemas.datacontract.org/2004/07/GVP.GAL.API"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/GVP.GAL.API">
			<xs:import namespace="http://schemas.datacontract.org/2004/07/GVP.GAL.Model" />
			<xs:complexType name="ResultDataContractOfboolean">
				<xs:sequence>
					<xs:element minOccurs="0" name="StatusCode" type="q1:StatusCode"
						xmlns:q1="http://schemas.datacontract.org/2004/07/GVP.GAL.Model" />
					<xs:element minOccurs="0" name="Severity" type="q2:Severity"
						xmlns:q2="http://schemas.datacontract.org/2004/07/GVP.GAL.Model" />
					<xs:element minOccurs="0" name="StatusMessage" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="Content" type="xs:boolean" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ResultDataContractOfboolean" nillable="true"
				type="tns:ResultDataContractOfboolean" />
		</xs:schema>
		<xs:schema elementFormDefault="qualified"
			targetNamespace="http://schemas.datacontract.org/2004/07/GVP.GAL.Model"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/GVP.GAL.Model">
			<xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
			<xs:simpleType name="StatusCode">
				<xs:restriction base="xs:string">
					<xs:enumeration value="NotImplemented">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">-3</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="NotSupported">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">-2</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UnknownError">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">-1</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="OK">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">0</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidInstanceId">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidPlatformId">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">2</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserAlreadyExists">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">3</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserDoesNotExist">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">4</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ProductDoesNotExist">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">5</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ProductAlreadyDeleted">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">6</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserAlreadyHasSubscription">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">7</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserDoesnotHaveSubscription">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">8</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserDoesnotHaveProduct">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">8</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserIsAlreadyEnabled">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">9</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserIsAlreadyDisabled">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">10</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="CannotDeleteEnabledUser">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">11</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="MissingMandatoryParameter">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">12</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidParameter">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">13</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidParameterValue">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">14</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Wrongorunsupportedparametervalue">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">15</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidParameterLength">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">16</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidParameterFormat">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">17</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidServiceId">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">18</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Serviceunavailable">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">100</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidPassword">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">102</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Usernotauthorized">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">103</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="CannotconnecttogSDP">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">196</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InternalservererroringSDP_D26">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">197</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InternalservererrorinOBsystem">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">198</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="OtherAuthenticationError">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">199</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ProductAlreadyExists">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">202</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidChargingClass">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">203</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InternalservererroringSDP">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">297</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="OtherProductLoadingError">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">299</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ServiceDisabled">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">303</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="OtherPurchaseError">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">399</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ProductAlreadyInCancelling">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">400</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ProductAlreadyInTrial">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">401</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="TrialNotAllowed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">402</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="EndDateAlreadyExpired">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">403</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidInputValue">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1002</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidRequestedOperation">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1003</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Expectedparametermissing">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1020</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Wrongorunsupportedparameter">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1021</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="GenericClientError">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1099</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="SubscriptionExpiredError">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1100</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="SubscriptionInactiveError">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1101</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="PinDoesNotExist">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1102</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UserAccountDoesNotExist">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">700</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ExceptionInUMGDatabase">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">701</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidPinValuesInOTT">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">702</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidInputData">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">703</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ErrorInRollback">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">704</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="MultipleErrorsDetectedByUMG">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">705</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidSystemConfiguration">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">706</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UMG2MiBConnectionFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">708</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UMG2GALConnectionFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">709</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="IPTVConnector2UMGConnectorConnectionFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">711</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidPrincipalId">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">800</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="EmptyGroups">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">801</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="TooManyGroups">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">802</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="PrincipalIdDoesNotExist">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">803</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="NoDefaultServiceGroup">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">804</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ServiceGroupNameNullOrEmpty">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">805</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ServiceGroupDoesNotExists">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">806</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="AccountIsNull">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">807</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="AccountExternalIdIsNullOrEmpty">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">808</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="DeviceIdIsEmpty">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">809</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="DeviceExternalIdIsNullOrEmpty">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">810</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="CreateAccountFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">811</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="AccountAlreadyExixts">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">812</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="DeviceExternalIdAlreadyExists">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">813</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UsernameIsNullOrEmpty">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">814</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidDevice">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">816</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="DeviceExternalIdAlreadySet">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">817</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="InvalidPin">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">818</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="NullRequestOrMandatoryParameter">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">819</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="DeviceExistsForThisAccount">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">820</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="BillingRecordExistsForThisAccount">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">821</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UsersExistsForThisAccount">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">822</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="BillingRecordDoesNotExistForThisAccount">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">823</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UsersDoesNotExistForThisAccount">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">824</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="DeviceDoesNotBelongToAccount">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">825</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="DeviceDoesNotExist">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">826</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UpdateDeviceFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">827</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UpdateAccountFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">828</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="NegativeHDStreams">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">829</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="NegativeSDStreams">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">830</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="TooManySDStreams">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">831</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="FailedToUpdateAllAccountValues">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">832</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UpdateAccountValuesFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">833</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UpdateAccountValuesIsNotSupportedOnServiceGroup">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">834</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ReadAllAccountValuesFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">835</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ReadGroupMembershipFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">836</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ReadDevicePinsFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">837</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UpdateEnableDateForPinByTypeFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">838</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UpdateDevicePinByTypeFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">839</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="SetStreamManagementProfileFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">840</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="GroupDoesNotExist">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">841</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="ReadGroupFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">842</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="IPTVConnector2MediaRoomConnectionFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">843</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="UMG2IPTVConnectorConnectionFailed">
						<xs:annotation>
							<xs:appinfo>
								<EnumerationValue
									xmlns="http://schemas.microsoft.com/2003/10/Serialization/">844</EnumerationValue>
							</xs:appinfo>
						</xs:annotation>
					</xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
			<xs:element name="StatusCode" nillable="true" type="tns:StatusCode" />
			<xs:simpleType name="Severity">
				<xs:restriction base="xs:string">
					<xs:enumeration value="Unknown" />
					<xs:enumeration value="Info" />
					<xs:enumeration value="Warning" />
					<xs:enumeration value="Error" />
				</xs:restriction>
			</xs:simpleType>
			<xs:element name="Severity" nillable="true" type="tns:Severity" />
		</xs:schema>
	</wsdl:types>
	<wsdl:message
		name="ITD_SubscriptionService_AddMultipleSubscription_InputMessage">
		<wsdl:part name="parameters" element="tns:AddMultipleSubscription" />
	</wsdl:message>
	<wsdl:message
		name="ITD_SubscriptionService_AddMultipleSubscription_OutputMessage">
		<wsdl:part name="parameters" element="tns:AddMultipleSubscriptionResponse" />
	</wsdl:message>
	<wsdl:message
		name="ITD_SubscriptionService_RemoveMultipleSubscription_InputMessage">
		<wsdl:part name="parameters" element="tns:RemoveMultipleSubscription" />
	</wsdl:message>
	<wsdl:message
		name="ITD_SubscriptionService_RemoveMultipleSubscription_OutputMessage">
		<wsdl:part name="parameters" element="tns:RemoveMultipleSubscriptionResponse" />
	</wsdl:message>
	<wsdl:message
		name="ITD_SubscriptionService_RemoveScheduledSubscriptions_InputMessage">
		<wsdl:part name="parameters" element="tns:RemoveScheduledSubscriptions" />
	</wsdl:message>
	<wsdl:message
		name="ITD_SubscriptionService_RemoveScheduledSubscriptions_OutputMessage">
		<wsdl:part name="parameters" element="tns:RemoveScheduledSubscriptionsResponse" />
	</wsdl:message>
	<wsdl:portType name="ITD_SubscriptionService">
		<wsdl:operation name="AddMultipleSubscription">
			<wsdl:input wsaw:Action="GVP.GAL/ITD_SubscriptionService/AddMultipleSubscription"
				message="tns:ITD_SubscriptionService_AddMultipleSubscription_InputMessage" />
			<wsdl:output
				wsaw:Action="GVP.GAL/ITD_SubscriptionService/AddMultipleSubscriptionResponse"
				message="tns:ITD_SubscriptionService_AddMultipleSubscription_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="RemoveMultipleSubscription">
			<wsdl:input
				wsaw:Action="GVP.GAL/ITD_SubscriptionService/RemoveMultipleSubscription"
				message="tns:ITD_SubscriptionService_RemoveMultipleSubscription_InputMessage" />
			<wsdl:output
				wsaw:Action="GVP.GAL/ITD_SubscriptionService/RemoveMultipleSubscriptionResponse"
				message="tns:ITD_SubscriptionService_RemoveMultipleSubscription_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="RemoveScheduledSubscriptions">
			<wsdl:input
				wsaw:Action="GVP.GAL/ITD_SubscriptionService/RemoveScheduledSubscriptions"
				message="tns:ITD_SubscriptionService_RemoveScheduledSubscriptions_InputMessage" />
			<wsdl:output
				wsaw:Action="GVP.GAL/ITD_SubscriptionService/RemoveMultipleSubscriptionResponse"
				message="tns:ITD_SubscriptionService_RemoveScheduledSubscriptions_OutputMessage" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BasicHttpBinding_ITD_SubscriptionService"
		type="tns:ITD_SubscriptionService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="AddMultipleSubscription">
			<soap:operation
				soapAction="GVP.GAL/ITD_SubscriptionService/AddMultipleSubscription"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="RemoveMultipleSubscription">
			<soap:operation
				soapAction="GVP.GAL/ITD_SubscriptionService/RemoveMultipleSubscription"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="RemoveScheduledSubscriptions">
			<soap:operation
				soapAction="GVP.GAL/ITD_SubscriptionService/RemoveScheduledSubscriptions"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="TD_SubscriptionService">
		<wsdl:port name="BasicHttpBinding_ITD_SubscriptionService"
			binding="tns:BasicHttpBinding_ITD_SubscriptionService">
			<soap:address
				location="http://localhost/Telefonica.UMG.GALConnector/TD_SubscriptionService.svc" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>