package com.telefonica.gal.SPAIN_TD_CustomerProvision.utils;

public enum ErrorCodeEnum {

    FORMAT_ERROR_USER_ID("GAL-02"),
    OBLIGATORY_FIELD_USER_ID("GAL-03"),
    FORMAT_ERROR_OPERATION_TYPE("GAL-04"),
    OBLIGATORY_FIELD_OPERATION_TYPE("GAL-05"),
    FORMAT_ERROR_GEOGRAFIC_AREA("GAL-10"),
    OBLIGATORY_FIELD_GEOGRAFIC_AREA("GAL-11"),
    FORMAT_ERROR_USER_TYPE("GAL-13"),
    OBLIGATORY_FIELD_USER_TYPE("GAL-14"),
    FORMAT_ERROR_SERVICE_TYPE("GAL-16"),
    OBLIGATORY_FIELD_SERVICE_TYPE("GAL-17"),
    FORMAT_ERROR_DEVICE("GAL-24"),
    OBLIGATORY_FIELD_DEVICE("GAL-25"),
    FORMAT_ERROR_TV_SERVICE_ID("GAL-27"),
    OBLIGATORY_FIELD_TV_SERVICE_ID("GAL-28"),
    FORMAT_ERROR_VOD_SERVICE_ID("GAL-30"),
    OBLIGATORY_FIELD_VOD_SERVICE_ID("GAL-31"),
    FORMAT_ERROR_POP("GAL-33"),
    OBLIGATORY_FIELD_POP("GAL-34"),
    OBLIGATORY_FIELD_OPERATOR_BONUS("GAL-43"),
    OBLIGATORY_FIELD_OPERATION_OPERATOR_BONUS("GAL-46"),
    FORMAT_ERROR_OPERATION_OPERATOR_BONUS("GAL-47"),
    OBLIGATORY_FIELD_TV_PACKACGE_OPERATION("GAL-48"),
    FORMAT_ERROR_TV_SERVICE_OPER("GAL-49"),
    OBLIGATORY_FIELD_TV_SERVICE_OPER("GAL-50"),
    FORMAT_ERROR_VOD_SERVICE_OPER("GAL-51"),
    OBLIGATORY_FIELD_SUSCRIBER_LINE_UPSTREAM("GAL-75"),
    FORMAT_ERROR_SUSCRIBER_LINE_UPSTREAM("GAL-76"),
    OBLIGATORY_FIELD_SUSCRIBER_LINE_DOWNSTREAM("GAL-77"),
    FORMAT_ERROR_SUSCRIBER_LINE_DOWNSTREAM("GAL-78"),
    FORMAT_ERROR_ADDRESSING("GAL-83"),
    FORMAT_ERROR_MAX_NUM_STBS("GAL-86"),
    FORMAT_ERROR_OPERATION_ID("GAL-200"),
    OBLIGATORY_FIELD_OPERATION_ID("GAL-201");

    private String value;

    private ErrorCodeEnum(String value) {
        this.value= value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
